#!/usr/bin/env ruby

require 'listen_sql'
require 'coderay'

def usage(message=nil)
  text = <<-TEXT
  Usage
  =====

    exec_sql DBNAME SRC [--no-color]

      DBNAME - database name to pass to `psql`

      SRC - source SQL file to run.

      --no-color - to disable ANSI escape codes
  TEXT

  if message
    puts message
    puts
    puts text
    exit(1)
  end
  puts text
end

db_name = ARGV.shift || usage('DBNAME should be first argument or set PGDATABASE in ENV!')
src = ARGV.shift || usage('SRC should be second argument!')
no_color = ARGV.detect{|a| a == '--no-color'}
ListenSql.exec_sql(db_name, src, color: !no_color)
