#!/usr/bin/env ruby

# Listens for any SQL file changes and executes them using the default PSQL
# settings.

require 'listen'
require 'listen_sql'

def usage(message=nil)
  text = <<-TEXT
listen_sql DIR DBNAME
# DIR - directory contains SQL files
# DBNAME - Postgres DB name to passed to `psql` command. 
  TEXT
  if message
    puts message
    puts
    puts text
    exit(1)
  end
  puts text
end

dir = ARGV.shift || usage('DIR is required as first argument!')
db_name = ARGV.shift || ENV['PGDATABASE'] || usage('DBNAME should be second argument or set PGDATABASE in ENV!')

listener = Listen.to(dir, only: /\.sql$/) do |modified, _|
  modified.each do |file|
    ListenSql.exec_sql(db_name, file, color: true)
  end
end

listener.start # not blocking
puts "Watching for changes to #{dir}"
puts "<CTRL-C> to quit"
sleep
